export interface WittyPersonalityProfile {
  code: string;
  name: string;
  tagline: string;
  bio: string;
  superpower: string;
  kryptonite: string;
  quote: string;
  advice: string;
  traits: string[];
}

export const WITTY_PERSONALITY_PROFILES: Record<string, WittyPersonalityProfile> = {
  BOSS: {
    code: "BOSS",
    name: "The Boss — Thủ Lĩnh Uy Quyền",
    tagline: "Sinh ra để gánh team, gánh luôn cả thế giới!",
    bio: "Bạn là kiểu người nếu không làm sếp thì cũng làm trùm trường hoặc chủ hộ. Trong mọi cuộc vui hay công việc, bạn luôn tự động bật chế độ chỉ huy. Bạn sẵn sàng xả thân gánh team, nhưng thỉnh thoảng cũng phải than đau lưng vì gánh quá nhiều!",
    superpower: "Tầm nhìn xa 10km, ra quyết định nhanh như chớp và bảo vệ đồng đội tới cùng.",
    kryptonite: "Rất ghét bị người khác chỉ tay năm ngón hoặc làm việc rề rà.",
    quote: "“Tóm lại là nghe tôi, không tranh luận thêm nữa!”",
    advice: "Thỉnh thoảng thả lỏng ra xíu, thế giới vẫn xoay mà không cần bạn làm thuyền trưởng đâu!",
    traits: ["Lãnh đạo", "Quyết đoán", "Bản lĩnh", "Gánh team"],
  },
  CTRL: {
    code: "CTRL",
    name: "The Controller — Trùm Kiếm Soát",
    tagline: "Sống bằng kế hoạch, thở bằng checklist!",
    bio: "Bạn sống bằng kế hoạch, thở bằng checklist và đi ngủ bằng báo thức lặp lại 5 lần. Nếu kế hoạch bị bể 1%, thế giới của bạn cũng bể theo. Bạn chưa bao giờ quên chìa khóa nhà hay làm mất căn cước công dân.",
    superpower: "Kỷ luật thép, soi chi tiết đỉnh cao, quản lý rủi ro tuyệt đối.",
    kryptonite: "Dễ nổi điên khi đồ đạc bị dịch chuyển 1cm hoặc bạn bè đến trễ 2 phút.",
    quote: "“File Excel đâu? Sao không làm đúng quy trình?”",
    advice: "Hãy học cách 'kệ đi', đôi khi sự ngẫu hứng lại mang tới niềm vui bất ngờ đấy!",
    traits: ["Kỷ luật", "Chi tiết", "Cẩn thận", "Hệ thống"],
  },
  SEXY: {
    code: "SEXY",
    name: "SEXY — Linh Thú Quyến Rũ",
    tagline: "Hào quang tự động bật, thính rơi vãi khắp nơi!",
    bio: "Chỉ cần bước vào phòng là hào quang của bạn tự động bật lên. Bạn không cố tình thả thính, nhưng sự tinh tế và khí chất tự nhiên của bạn cứ tự rơi vãi làm bao tâm hồn xao xuyến.",
    superpower: "Giao tiếp tinh tế, EQ cao ngất ngưởng, khí chất cuốn hút bẩm sinh.",
    kryptonite: "Dễ bị hiểu lầm là đào hoa, mệt mỏi vì lúc nào cũng phải giữ hình ảnh đẹp.",
    quote: "“Ủa, tôi đâu có làm gì đâu mà mọi người cứ nhìn vậy?”",
    advice: "Thỉnh thoảng mặc đồ bộ đi đổ rác cũng chẳng sao đâu, bạn vẫn đẹp mà!",
    traits: ["Quyến rũ", "Tinh tế", "EQ cao", "Cuốn hút"],
  },
  DRUNK: {
    code: "DRUNK",
    name: "DRUNK — Thánh Say Ma Thuật",
    tagline: "Ban ngày thiền sư, ban đêm yêu cả vũ trụ!",
    bio: "Ban ngày bạn điềm tĩnh trầm mặc như thiền sư, nhưng ban đêm khi cồn ngấm vào là hóa thành chiếc loa phát thanh yêu thương cả vũ trụ! Bạn ôm hết người này tới người khác để tâm sự 7749 câu chuyện đời.",
    superpower: "Chân thành tuyệt đối, bao dung mọi lỗi lầm, kết bạn được với cả bàn bên.",
    kryptonite: "Sáng hôm sau tỉnh dậy đọc lại tin nhắn đêm qua và muốn chuyển sang sao Hỏa sống.",
    quote: "“Anh em mình là một gia đình! Nào cụm ly 100%!”",
    advice: "Uống ít nước lọc trước khi đi ngủ và giao điện thoại cho bạn thân giữ giùm nhé!",
    traits: ["Chân thành", "Phóng khoáng", "Cởi mở", "Yêu đời"],
  },
  SOLO: {
    code: "SOLO",
    name: "SOLO — Độc Hành Huyền Bí",
    tagline: "Một mình nhưng không cô đơn, chỉ là thích yên tĩnh!",
    bio: "Sống trong thế giới nội tâm cực kỳ phong phú. Bạn ghét chốn đông người, thích đi ăn một mình, xem phim một mình và đi du lịch một mình. Sự độc lập của bạn làm người khác vừa nể vừa tò mò.",
    superpower: "Nội lực thâm sâu, tư duy độc lập, không phụ thuộc cảm xúc vào người khác.",
    kryptonite: "Dễ bị coi là chảnh chọe, thờ ơ với thế giới xung quanh.",
    quote: "“Vui lòng không gọi điện, hãy nhắn tin. Mà nhắn chưa chắc trả lời.”",
    advice: "Bước ra ngoài hít thở chút không khí đi, thế giới bên ngoài cũng vui lắm!",
    traits: ["Độc lập", "Sâu sắc", "Bí ẩn", "Tự chủ"],
  },
  MONK: {
    code: "MONK",
    name: "MONK — Thiền Sĩ Thanh Tịnh",
    tagline: "Tâm bình thản trước mọi sóng gió cuộc đời!",
    bio: "Tâm bạn bình thản trước mọi drama. Dù deadline dí sát đít hay thế giới ngoài kia bùng nổ, bạn vẫn thong thả ngồi uống trà ngắm mưa rơi. Không gì có thể làm xáo trộn sự bình yên của bạn.",
    superpower: "Sự điềm tĩnh kinh ngạc, thấu hiểu quy luật tự nhiên và lòng vị tha.",
    kryptonite: "Đôi khi quá lười tranh đấu, thiếu động lực bứt phá.",
    quote: "“Tùy duyên đi, cái gì đến sẽ đến, cái gì đi cứ để nó đi.”",
    advice: "Bình thản là tốt, nhưng thỉnh thoảng hãy bùng nổ chút năng lượng tuổi trẻ nhé!",
    traits: ["Điềm tĩnh", "Thanh thản", "Vị tha", "Sâu sắc"],
  },
  DIOR: {
    code: "DIOR",
    name: "Dior-s — Quý Tộc Sang Chảnh",
    tagline: "Thà nhịn ăn chứ quyết không nhịn mặc đẹp!",
    bio: "Bạn là tín đồ của cái đẹp và sự hoàn hảo. Gu thời trang và thẩm mỹ của bạn cực cao. Bạn không chấp nhận sự xuề xòa hay nhạt nhẽo trong cuộc sống.",
    superpower: "Gu nghệ thuật tinh tế, biết cách tận hưởng những điều tốt đẹp nhất.",
    kryptonite: "Ví tiền thường xuyên rơi vào tình trạng báo động đỏ do chốt đơn cuồng nhiệt.",
    quote: "“Đời ngắn lắm, sao phải sống một cuộc đời nhạt nhẽo?”",
    advice: "Hãy nhớ tích lũy quỹ tiết kiệm trước khi chốt đơn món đồ xa xỉ tiếp theo!",
    traits: ["Sang chảnh", "Gu cao", "Tế nhị", "Hoàn hảo"],
  },
  JOKER: {
    code: "JOKER",
    name: "JOKE-R — Hề Sĩ Vui Vẻ",
    tagline: "Chiến thần pha trò, nơi đâu có bạn ở đó có tiếng cười!",
    bio: "Bạn là cây hài của mọi cuộc vui. Nơi đâu có bạn xuất hiện, không khí ở đó lập tức trở nên nhộn nhịp rộn rã. Bạn có khả năng biến mọi nỗi buồn thành câu chuyện cười hài hước.",
    superpower: "Năng lượng tích cực dồi dào, giải tỏa căng thẳng cho mọi người cực tốt.",
    kryptonite: "Thường giấu nỗi buồn sau nụ cười, khó bộc lộ cảm xúc thật khi tổn thương.",
    quote: "“Cuộc đời là một vở kịch, tại sao không cười lên chứ?”",
    advice: "Bạn không cần phải lúc nào cũng làm hề. Bạn có quyền buồn và cần sự vỗ về!",
    traits: ["Hài hước", "Năng lượng", "Vui vẻ", "Hòa đồng"],
  },
  DEAD: {
    code: "DEAD",
    name: "DEAD — Chiến Binh Bất Tử",
    tagline: "Tái sinh từ nghịch cảnh, không gì quật ngã được!",
    bio: "Trải qua 81 kiếp nạn của cuộc đời nhưng bạn vẫn lầm lì bước tiếp. Càng bị vùi dập, bạn càng tái sinh mạnh mẽ hơn. Sự kiên cường của bạn khiến người khác phải kiêng nể.",
    superpower: "Sức chịu đựng vô hạn, ý chí kiên cường, nội tâm trầm mặc sâu sắc.",
    kryptonite: "Hay nhìn đời qua lăng kính u uất, khó tin tưởng người khác.",
    quote: "“Điều gì không giết được tôi sẽ làm tôi lì hơn!”",
    advice: "Thế giới này vẫn còn nhiều điều ấm áp, hãy mở lòng đón nhận ánh nắng nào!",
    traits: ["Kiên cường", "Lì lợm", "Tái sinh", "Bất tử"],
  },
  ZZZZ: {
    code: "ZZZZ",
    name: "ZZZZ — Ẩn Sĩ Mộng Mơ",
    tagline: "Thánh ngủ vũ trụ, thế giới thực nằm trong giấc mơ!",
    bio: "Bạn có thể ngủ ở mọi tư thế, mọi thời điểm. Với bạn, giấc ngủ là chiếc cổng dẫn vào vương quốc mộng mơ giàu sang tưởng tượng nhất.",
    superpower: "Trí tưởng tượng phong phú, tâm hồn bình yên, không bon chen.",
    kryptonite: "Dễ bỏ lỡ các cơ hội tuyệt vời vì... bận ngủ.",
    quote: "“Nói ít thôi, cho tôi ngủ thêm 5 phút nữa...”",
    advice: "Đặt báo thức ở xa giường và bắt đầu thực hiện những ước mơ tuyệt vời của bạn đi!",
    traits: ["Mộng mơ", "Bình yên", "Tự do", "Thư thái"],
  },
  ATMR: {
    code: "ATMR",
    name: "ATM-er — Cây ATM Biết Đi",
    tagline: "Hào sảng vô bờ, bảo bối tài chính của bạn bè!",
    bio: "Bạn hào sảng, rộng lượng và luôn là người tranh giành trả tiền chầu nước. Thấy bạn bè gặp khó khăn là tay bạn tự động rút ví ra hỗ trợ.",
    superpower: "Tốt bụng tuyệt đối, được mọi người yêu mến và tin tưởng tuyệt đối.",
    kryptonite: "Dễ bị kẻ xấu lợi dụng lòng tốt, ví tiền nhanh vơi.",
    quote: "“Để đó tôi lo! Mấy chuyện này có gì đâu!”",
    advice: "Hãy học cách nói 'KHÔNG' khi cần thiết và tự chăm sóc bản thân trước nhé!",
    traits: ["Hào sảng", "Tốt bụng", "Rộng lượng", "Uy tín"],
  },
  THANK: {
    code: "THANK",
    name: "THAN-K — Người Biết Ơn",
    tagline: "Trái tim ấm áp, biết ơn từng điều nhỏ bé!",
    bio: "Tâm hồn bạn tràn ngập tình yêu thương. Thấy chú mèo đi qua bạn cũng mỉm cười, thấy trời mưa bạn cũng cảm ơn cuộc đời vì đã tưới mát cây xanh.",
    superpower: "Lan tỏa năng lượng ấm áp, biết trân trọng từng khoảnh khắc nhỏ bé.",
    kryptonite: "Dễ xúc động, đôi khi quá nhạy cảm với thái độ của người khác.",
    quote: "“Cảm ơn cuộc đời mỗi ban mai thức dậy...”",
    advice: "Sự biết ơn của bạn là món quà, hãy giữ vững trái tim ấm áp này nhé!",
    traits: ["Biết ơn", "Ấm áp", "Nhạy cảm", "Chân thành"],
  },
  OHNO: {
    code: "OHNO",
    name: "OH-NO — Thánh Hoảng Hốt",
    tagline: "Chuyên gia lo xa, luôn có kế hoạch phòng rủi ro!",
    bio: "Bạn là chuyên gia lo xa của vũ trụ. Đi du lịch 2 ngày nhưng bạn mang theo cả tiệm thuốc thu nhỏ. Bạn luôn chuẩn bị sẵn sàng cho kịch bản tồi tệ nhất.",
    superpower: "Cẩn trọng tuyệt đối, khả năng dự phòng rủi ro cực cao.",
    kryptonite: "Hay tự làm mình căng thẳng bởi những kịch bản chưa bao giờ xảy ra.",
    quote: "“OH NO! Nhỡ đâu trời mưa rồi sập nhà thì sao?!”",
    advice: "Hít thở sâu nào! 99% những điều bạn lo lắng sẽ không xảy ra đâu!",
    traits: ["Cẩn trọng", "Lo xa", "Chu đáo", "Dự phòng"],
  },
  GOGO: {
    code: "GOGO",
    name: "GOGO — Chiến Thần Năng Lượng",
    tagline: "Không bao giờ ngồi yên, cháy hết mình với đam mê!",
    bio: "Bạn không bao giờ chịu ngồi yên một chỗ. Vừa xong việc này là bạn nháo nhào nhảy sang việc khác, lúc nào cũng tràn đầy sinh lực rực rỡ.",
    superpower: "Tốc độ hành động cực nhanh, truyền lửa tuyệt vời cho tập thể.",
    kryptonite: "Dễ bị kiệt sức (burnout) do không biết dừng lại đúng lúc.",
    quote: "“GOGO! Chiến thôi chờ gì nữa anh em ơi!”",
    advice: "Hãy dành thời gian nghỉ ngơi sạc pin, chạy nhanh quá dễ đứt xích đó!",
    traits: ["Năng nổ", "Tốc độ", "Nhiệt huyết", "Truyền cảm hứng"],
  },
  LOVR: {
    code: "LOVR",
    name: "LOVE-R — Kẻ Lãng Mạn Mộng Mơ",
    tagline: "Thở bằng tình yêu, sống bằng sự ngọt ngào!",
    bio: "Bạn sống vì tình yêu và thở bằng sự lãng mạn. Xem phim tình cảm là bạn khóc trôi nhà. Bạn luôn tin vào những câu chuyện cổ tích và tình yêu vĩnh cửu.",
    superpower: "Giàu cảm xúc, biết cách tạo ra bất ngờ và sự ngọt ngào cho đối phương.",
    kryptonite: "Dễ bị tổn thương sâu sắc khi tình yêu không như kỳ vọng.",
    quote: "“Tình yêu là sức mạnh duy nhất cứu rỗi thế giới này.”",
    advice: "Yêu người khác tốt đấy, nhưng nhớ yêu thương chính mình trước nhất nhé!",
    traits: ["Lãng mạn", "Ngọt ngào", "Giàu cảm xúc", "Chân thành"],
  },
  MUMM: {
    code: "MUMM",
    name: "MUM — Người Mẹ Quốc Dân",
    tagline: "Chu đáo tới từng chân răng, bảo bọc mọi người!",
    bio: "Bạn chu đáo tới từng chi tiết nhỏ. Đi chơi nhóm bạn luôn mang theo khăn giấy, nước rửa tay, sạc dự phòng và đồ ăn nhẹ cho cả hội.",
    superpower: "Khả năng chăm sóc bảo bọc tuyệt vời, tạo cảm giác an toàn cẩn thận.",
    kryptonite: "Hay lo lắng thái quá cho người khác mà quên mất chăm sóc bản thân.",
    quote: "“Ăn cơm chưa? Nhớ uống nhiều nước vào đấy nhé!”",
    advice: "Để mọi người tự trưởng thành chút đi, bạn cũng cần được chăm sóc mà!",
    traits: ["Chu đáo", "Bảo bọc", "Ấm áp", "Tận tụy"],
  },
  FAKE: {
    code: "FAKE",
    name: "FAKE — Bậc Thầy Núp Bóng",
    tagline: "Tắc kè hoa xã hội, 100 chiếc mặt nạ ứng biến!",
    bio: "Bạn là tắc kè hoa của thế giới tính cách. Gặp người nghiêm túc bạn nghiêm túc, gặp người quậy bạn quậy tới bến. Bạn nhập vai cực ngọt trong mọi hoàn cảnh.",
    superpower: "Khả năng thích nghi cực cao, giao thiệp rộng rãi không rào cản.",
    kryptonite: "Đôi khi quên mất con người thật của mình thực sự muốn gì.",
    quote: "“Tùy đối tượng thôi, tôi có 100 chiếc mặt nạ mà!”",
    advice: "Hãy dành không gian riêng để thả lỏng và sống thật với chính mình nhé!",
    traits: ["Linh hoạt", "Thích nghi", "Khéo léo", "Nhanh trí"],
  },
  OJBK: {
    code: "OJBK",
    name: "OJBK — Thánh Sao Cũng Được",
    tagline: "Dễ tính nhất hành tinh, lành tính vô bờ!",
    bio: "Bạn dễ tính nhất thế giới. Hỏi ăn gì cũng 'gì cũng được', đi đâu cũng 'sao cũng được'. Bạn cực kỳ lành tính và không thích tranh chấp.",
    superpower: "Dễ sống, không tranh chấp, mang lại sự dễ chịu cho mọi người xung quanh.",
    kryptonite: "Thiếu chính kiến, dễ bị cuốn theo quyết định của người khác.",
    quote: "“OK dĩ nhiên rồi (OJBK)! Sao cũng hợp lý hết!”",
    advice: "Thỉnh thoảng hãy dũng cảm nói ra ý kiến và mong muốn riêng của bạn!",
    traits: ["Dễ tính", "Lành tính", "Hòa nhã", "Thoải mái"],
  },
  MALO: {
    code: "MALO",
    name: "MALO — Khỉ Nho Hóm Hỉnh",
    tagline: "Lém lỉnh nhanh trí, ngôi sao của mọi cuộc vui!",
    bio: "Bạn lém lỉnh, nhanh trí và luôn có những trò đùa bất ngờ. Bạn không bao giờ chịu thua trong các cuộc tranh luận vui vẻ.",
    superpower: "Linh hoạt, ứng biến cực nhanh, đầu óc nảy số liên tục.",
    kryptonite: "Đôi khi đùa quá đà làm người khác chạnh lòng.",
    quote: "“Chuyện nhỏ như con thỏ, để tôi ra tay cho xem!”",
    advice: "Đùa vui đúng lúc đúng chỗ sẽ giúp bạn trở thành ngôi sao mọi cuộc trò chuyện!",
    traits: ["Lém lỉnh", "Nhanh trí", "Hóm hỉnh", "Ứng biến"],
  },
  WOCI: {
    code: "WOCI",
    name: "WOC! — Thánh Ôi Chao",
    tagline: "Biểu cảm sống động, khán giả cuồng nhiệt nhất!",
    bio: "Biểu cảm của bạn sống động như ảnh GIF. Bất kỳ sự việc nhỏ nào cũng có thể làm bạn trầm ồ thán phục và tạo năng lượng cho câu chuyện.",
    superpower: "Chân thật, giàu cảm xúc, làm khán giả nhiệt thành nhất cho mọi người.",
    kryptonite: "Dễ bị cuốn theo cảm xúc bộc phát mà thiếu sự tĩnh lặng.",
    quote: "“WOC! Thật luôn?! Không thể tin nổi luôn đó!”",
    advice: "Giữ chút bình tĩnh để quan sát toàn cảnh trước khi phản ứng nhé!",
    traits: ["Sống động", "Chân thật", "Nhiệt thành", "Cảm xúc"],
  },
  THINK: {
    code: "THINK",
    name: "THIN-K — Nhà Triết Học Đêm Muộn",
    tagline: "Trăn trở nhân sinh, phân tích bản chất vũ trụ!",
    bio: "Đêm muộn là lúc đầu óc bạn bật chế độ phân tích vũ trụ. Bạn luôn trăn trở về ý nghĩa cuộc sống, bản chất con người và quy luật sự vật.",
    superpower: "Tư duy sâu sắc, logic mạch lạc, cái nhìn thấu đáo bản chất.",
    kryptonite: "Hay bị mất ngủ vì suy nghĩ quá nhiều chuyện trên trời dưới đất.",
    quote: "“Tại sao chúng ta lại ở đây? Mục đích của vũ trụ là gì?”",
    advice: "Đôi khi cuộc sống chỉ đơn giản là ăn một bữa ngon và ngủ một giấc sâu!",
    traits: ["Sâu sắc", "Triết học", "Tư duy", "Logic"],
  },
  SHIT: {
    code: "SHIT",
    name: "SHIT — Thánh Thẳng Thắn",
    tagline: "Khẩu xà tâm phật, miệng gắt nhưng lòng ấm!",
    bio: "Bạn thuộc tuýp khẩu xà tâm phật. Miệng hay nói lời thẳng thắn gắt gỏng, nhưng thấy bạn bè gặp chuyện là sẵn sàng lao vào xả thân giúp đỡ.",
    superpower: "Thẳng thắn tuyệt đối, không giả tạo, cực kỳ trung thành với bạn bè.",
    kryptonite: "Lời nói thẳng quá dễ làm tổn thương những tâm hồn mỏng mảnh.",
    quote: "“Nói thẳng ra là dở tệ, nhưng thôi để tôi chỉ cho làm!”",
    advice: "Tiết chế lại sự gắt gao xíu, món ăn ngon cần chút gia vị ngọt ngào mà!",
    traits: ["Thẳng thắn", "Chân thật", "Trung thành", "Bản lĩnh"],
  },
  POOR: {
    code: "POOR",
    name: "POOR — Thánh Than Nghèo",
    tagline: "Mở miệng là than nghèo, tài khoản luôn có quỹ xịn!",
    bio: "Mở miệng ra là bạn than 'Tôi nghèo lắm', nhưng trong tài khoản tiết kiệm của bạn luôn có quỹ dự phòng xịn xò. Bạn thích sống thực tế và tiết kiệm.",
    superpower: "Quản lý tài chính cực giỏi, thực tế, không lãng phí.",
    kryptonite: "Đôi khi quá keo kiệt với chính bản thân mình.",
    quote: "“Thôi đắt lắm, không có tiền đâu...”",
    advice: "Hãy thưởng cho bản thân một chút niềm vui xứng đáng sau những nỗ lực!",
    traits: ["Thực tế", "Tiết kiệm", "Quản lý tốt", "Cẩn thận"],
  },
  IMSB: {
    code: "IMSB",
    name: "IMSB — Thánh Ngu Ngơ Trẻ Thơ",
    tagline: "Tâm hồn trong sáng, nhìn đời qua lăng kính màu hồng!",
    bio: "Tâm hồn bạn trong sáng như tờ giấy trắng. Ai nói gì bạn cũng tin, ngây thơ vô số tội và luôn nhìn đời qua màu hồng ngập tràn hy vọng.",
    superpower: "Đáng yêu, chân thành, mang lại sự nhẹ nhõm cho người bên cạnh.",
    kryptonite: "Dễ bị lừa bởi những lời đường mật.",
    quote: "“Ủa vậy hả? Sao tôi không biết gì hết vậy ta?”",
    advice: "Giữ sự ngây thơ nhưng nhớ trang bị thêm chút cảnh giác trước thế giới nhé!",
    traits: ["Trong sáng", "Trẻ thơ", "Ngây thơ", "Đáng yêu"],
  },
  FUCK: {
    code: "FUCK",
    name: "FUCK — Kẻ Hoang Dã Phá Cách",
    tagline: "Ghét mọi quy tắc, tự do tuyệt đối!",
    bio: "Bạn ghét mọi sự gò bó và quy tắc cứng nhắc. Bạn sống tự do, phóng khoáng và thích làm những điều người khác không bao giờ ngờ tới.",
    superpower: "Sáng tạo bùng nổ, dũng cảm phá vỡ giới hạn, cá tính cực mạnh.",
    kryptonite: "Dễ nổi loạn, khó làm việc trong môi trường gò bó kỷ luật.",
    quote: "“Quy tắc sinh ra là để phá vỡ mà!”",
    advice: "Tự do tuyệt vời, nhưng giữ chút kỷ luật sẽ giúp bạn tiến xa hơn nữa!",
    traits: ["Hoang dã", "Phá cách", "Tự do", "Sáng tạo"],
  },
  IMFW: {
    code: "IMFW",
    name: "IMFW — Thánh Vô Dụng Yêu Đời",
    tagline: "Triết lý nằm yên, không ganh đua với đời!",
    bio: "Triết lý sống của bạn là: 'Nằm yên mặc kệ đời'. Bạn không ganh đua với ai, thong thả tận hưởng những niềm vui nhỏ bé mỗi ngày.",
    superpower: "Thoải mái, không áp lực, tâm lý vô vi tự tại.",
    kryptonite: "Thiếu chí tiến thủ, dễ hài lòng với hiện tại quá sớm.",
    quote: "“Gió tầng nào gặp mây tầng đó, tôi nằm tầng 1 cho lành.”",
    advice: "Thỉnh thoảng hãy thử đặt một mục tiêu nhỏ để thử thách bản thân xem sao!",
    traits: ["An nhiên", "Thư thái", "Thoải mái", "Không gánh nặng"],
  },
  HHHH: {
    code: "HHHH",
    name: "HHHH — Bậc Thầy Giả Chết",
    tagline: "Khi có biến lập tức tàng hình, ẩn thân chờ cơ hội!",
    bio: "Bạn là bậc thầy giấu mình. Khi có drama hay biến cố, bạn lập tức giả chết ẩn thân, chờ sóng êm biển lặng mới thong thả bước ra.",
    superpower: "Khả năng sinh tồn và tránh rắc rối đạt cấp độ thượng thừa.",
    kryptonite: "Hay né tránh xung đột ngay cả khi cần dũng cảm đối mặt.",
    quote: "“Tôi không có ở đây, mọi người cứ tự nhiên...”",
    advice: "Dũng cảm lên! Đôi khi bước ra ánh sáng sẽ giúp bạn tìm thấy sức mạnh thực sự!",
    traits: ["Ẩn thân", "Tránh rắc rối", "Sinh tồn", "Khéo léo"],
  },
};

export function getWittyProfile(code: string): WittyPersonalityProfile {
  if (!code) return WITTY_PERSONALITY_PROFILES.BOSS;
  const upper = code.trim().toUpperCase();

  // Code normalization mapping
  const normalizedKey = 
    upper === "ATM" ? "ATMR" :
    upper === "DIOR" ? "DIOR" :
    upper === "JOKER" || upper === "JOKE-R" ? "JOKER" :
    upper === "LOVR" || upper === "LOVE-R" ? "LOVR" :
    upper === "MUM" ? "MUMM" :
    upper === "OHNO" || upper === "OH-NO" ? "OHNO" :
    upper === "THANK" || upper === "THAN-K" ? "THANK" :
    upper === "THINK" || upper === "THIN-K" ? "THINK" :
    upper === "WOC" || upper === "WOCI" ? "WOCI" :
    upper;

  return WITTY_PERSONALITY_PROFILES[normalizedKey] || WITTY_PERSONALITY_PROFILES[code] || {
    code,
    name: `${code} — Linh Thú Độc Bản`,
    tagline: "Một linh thú mang trường năng lượng đặc biệt!",
    bio: "Linh thú độc đáo mang đến góc nhìn mới mẻ và thú vị về tính cách của bạn trong thế giới TESTDII.",
    superpower: "Độc bản, khác biệt, khó nắm bắt.",
    kryptonite: "Đôi khi làm người khác bối rối vì sự độc đáo.",
    quote: "“Tôi là chính tôi, không đụng hàng!”",
    advice: "Hãy tiếp tục giữ vững bản sắc riêng của bạn!",
    traits: ["Độc bản", "Bí ẩn", "Cá tính"],
  };
}
