export interface WittyPersonalityProfile {
  code: string;
  name: string;
  tagline: string;
  bio: string;
  superpower: string;
  kryptonite: string;
  quote: string;
  advice: string;
  exampleScenario: string;
  traits: string[];
}

export const WITTY_PERSONALITY_PROFILES: Record<string, WittyPersonalityProfile> = {
  BOSS: {
    code: "BOSS",
    name: "The Boss — Thủ Lĩnh Uy Quyền",
    tagline: "Sinh ra để gánh team, gánh luôn cả thế giới!",
    bio: "Bạn là kiểu người nếu không làm sếp thì cũng làm trùm trường, hội trưởng hoặc 'ông trùm' của nhóm bạn. Trong mọi cuộc vui hay đồ án học tập, bạn tự động bật chế độ chỉ huy 100%. Bạn sẵn sàng xả thân gánh team tới phút 89, nhưng thỉnh thoại cũng than đau lưng vì phải gánh mấy đứa bạn tạ quá!",
    superpower: "Tầm nhìn xa 10km, định hướng chuẩn đét, quyết đoán như chớp và bảo vệ đồng đội tới cùng.",
    kryptonite: "Rất ghét bị người khác chỉ tay năm ngón, làm việc lề mề hoặc 'chuyển giao deadline' mà không xin phép.",
    quote: "“Tóm lại là nghe tôi, phân công vậy rồi, cấm ai bàn lùi nữa!”",
    advice: "Thỉnh thoảng thả lỏng ra xíu nào, quả đất vẫn tự quay mà không cần bạn làm thuyền trưởng 24/7 đâu!",
    exampleScenario: "Đi ăn lẩu nhóm 10 người, khi mọi người còn đang phân vân 'ăn gì nhỉ', bạn đã chốt ngay combo Lẩu Thái, phân công đứa đi lấy nước chấm, đứa đi lấy đồ cuốn và canh giờ thả bò!",
    traits: ["Lãnh đạo", "Quyết đoán", "Bản lĩnh", "Gánh team"],
  },
  CTRL: {
    code: "CTRL",
    name: "The Controller — Trùm Kiểm Soát",
    tagline: "Sống bằng kế hoạch, thở bằng checklist, ngủ bằng 5 báo thức!",
    bio: "Bạn sống bằng kế hoạch tỉ mỉ, thở bằng checklist Notion/Excel và đặt báo thức lặp lại 5 phút/lần. Bạn biết chính xác trong ví mình còn bao nhiêu tờ tiền và ngày này năm sau mình sẽ làm gì. Nếu kế hoạch lệch đi 1%, tâm trí bạn cũng 'bão giật cấp 12'!",
    superpower: "Kỷ luật thép, soi chi tiết đỉnh cao như kính hiển vi, quản lý rủi ro tuyệt đối.",
    kryptonite: "Dễ nổi điên khi đồ đạc trên bàn bị ai đó dịch chuyển 1cm hoặc bạn bè hẹn 7h mà 7h15 mới xuất phát.",
    quote: "“File Excel itinerary chuyến đi đâu rồi? Sao không làm đúng quy trình?”",
    advice: "Hãy thử học cách 'kệ đi!', đôi khi những chuyến đi không lịch trình lại mang tới niềm vui bùng nổ đấy!",
    exampleScenario: "Đi du lịch cùng bạn bè, bạn mang sẵn tăm bông, sạc dự phòng 20.000mAh, thuốc cảm, bản đồ in ép plastic và lịch trình chi tiết từng phút từ 6:00 AM tới 10:00 PM!",
    traits: ["Kỷ luật", "Chi tiết", "Cẩn thận", "Hệ thống"],
  },
  SEXY: {
    code: "SEXY",
    name: "SEXY — Linh Thú Quyến Rũ",
    tagline: "Hào quang tự động bật, thính rơi vãi khắp nơi!",
    bio: "Chỉ cần bạn bước chân vào phòng là hào quang tự động sáng rực lên. Bạn không cố tình thả thính, nhưng sự tinh tế, gu ăn mặc chất lừ cùng thần thái 'cool ngầu' cứ tự rơi vãi làm bao tâm hồn điên đảo. Bạn là tâm điểm thu hút mọi ánh nhìn mà không cần cố gắng.",
    superpower: "Giao tiếp tinh tế đỉnh cao, EQ chạm trần, sức cuốn hút bẩm sinh làm người đối diện đổ gục.",
    kryptonite: "Hay bị hiểu nhầm là kẻ đào hoa lăng nhăng, và mệt mỏi vì lúc nào cũng phải giữ hình ảnh đẹp hoàn hảo.",
    quote: "“Ủa, tôi chỉ cười xã giao thôi mà, sao người ta lại xin số nữa rồi?”",
    advice: "Thỉnh thoảng mặc đồ bộ đi đổ rác hay lỡ tóc bết chút cũng chẳng sao đâu, bạn vẫn có chất riêng mà!",
    exampleScenario: "Đi đu idol hoặc dự tiệc trường, bạn chỉ cần vuốt lại mái tóc và mỉm cười nhẹ nhàng là ngay lập tức có 3 người ra xin Instagram!",
    traits: ["Quyến rũ", "Tinh tế", "EQ cao", "Cuốn hút"],
  },
  DRUNK: {
    code: "DRUNK",
    name: "DRUNK — Thánh Say Ma Thuật",
    tagline: "Ban ngày thiền sư điềm tĩnh, ban đêm cồn ngấm là yêu cả vũ trụ!",
    bio: "Ban ngày bạn điềm tĩnh, nói năng chừng mực như một vị thiền sư tĩnh lặng. Nhưng ban đêm, khi cồn hoặc chất kích thích chạm vào môi, bạn hóa thành chiếc 'loa phát thanh tình yêu' sẵn sàng ôm cả thế giới! Bạn có thể kết bạn với chú bảo vệ, nói chuyện triết học với bàn bên cạnh.",
    superpower: "Chân thành tuyệt đối, giải tỏa mọi rào cản xã giao, kết bạn siêu tốc với bất kỳ ai trong bán kính 100m.",
    kryptonite: "Sáng hôm sau tỉnh dậy mở điện thoại xem lại tin nhắn đêm qua và muốn bắt phi thuyền sang Sao Hỏa sống ẩn dật.",
    quote: "“Anh em mình là một gia đình! Tao thề tao yêu tụi mày nhất trên đời này!”",
    advice: "Uống nhiều nước lọc trước khi đi ngủ và nhớ giao điện thoại cho bạn thân giữ giùm trước khi bắt đầu chầu nhậu nhé!",
    exampleScenario: "Đi tiệc sinh nhật bạn, uống tới ly thứ 3 là bạn bắt đầu nắm tay anh bồi bàn khuyên anh ấy sống hạnh phúc và hát karaoke bài 'Cát Bụi' bằng cả tâm hồn!",
    traits: ["Chân thành", "Phóng khoáng", "Cởi mở", "Yêu đời"],
  },
  SOLO: {
    code: "SOLO",
    name: "SOLO — Độc Hành Huyền Bí",
    tagline: "Một mình nhưng không cô đơn, chỉ là thấy con người hơi phiền!",
    bio: "Bạn sống trong một vũ trụ nội tâm cực kỳ phong phú và độc lập. Bạn thích đi ăn quán một mình, xem phim rạp một mình và tự đi chill mà không cần rủ ai. Sự lạnh lùng bí ẩn của bạn làm người khác vừa kiêng nể vừa tò mò muốn khám phá.",
    superpower: "Nội lực thâm sâu, tư duy độc lập sắc bén, không bị phụ thuộc cảm xúc vào bất kỳ ai.",
    kryptonite: "Dễ bị bạn bè gán nhãn là 'chảnh chọe', xa cách và bỏ lỡ một số kết nối ấm áp.",
    quote: "“Vui lòng không gọi điện thoại, hãy nhắn tin. Mà nhắn chưa chắc tôi đã trả lời liền đâu.”",
    advice: "Mở cửa phòng bước ra ngoài hít thở chút không khí đi bạn ơi, thế giới ngoài kia cũng nhiều điều dễ thương lắm!",
    exampleScenario: "Cuối tuần bạn lẳng lặng ôm laptop ra một quán cà phê ẩn mình trong hẻm nhỏ, đeo tai nghe chống ồn ngồi đọc sách 5 tiếng liên tục mà không đụng vào mạng xã hội.",
    traits: ["Độc lập", "Sâu sắc", "Bí ẩn", "Tự chủ"],
  },
  MONK: {
    code: "MONK",
    name: "MONK — Thiền Sĩ Thanh Tịnh",
    tagline: "Tâm bình thản trước mọi drama, deadline dí vẫn ngắm mưa rơi!",
    bio: "Tâm bạn miễn nhiễm với mọi drama của thế giới. Dù ngoài kia người ta cãi nhau ầm ĩ hay deadline đang dí sát đít, bạn vẫn thong thả nhấp ngụm trà mát, ngắm mây bay và mỉm cười thanh thản. Bạn tin rằng mọi chuyện trên đời đều có quy luật tự nhiên của nó.",
    superpower: "Sự điềm tĩnh kinh ngạc, khả năng cân bằng tâm trí cực tốt, không bao giờ rơi vào hoảng loạn.",
    kryptonite: "Đôi khi bị coi là thiếu động lực phấn đấu, lười tranh đấu và dễ bằng lòng quá sớm.",
    quote: "“Tùy duyên đi bạn ơi, cái gì của mình sẽ là của mình, không phải của mình có ép cũng không được.”",
    advice: "Thanh tịnh là tuyệt vời, nhưng thỉnh thoại hãy bùng nổ chút năng lượng tuổi trẻ để bứt phá giới hạn nhé!",
    exampleScenario: "Trong nhóm chat lớp đang bùng nổ tranh cãi nảy lửa về bài tập nhóm, bạn gửi một sticker chú mèo đang ngủ kèm câu: 'Mọi người hạ hỏa ăn miếng bánh uống miếng nước đi nào'.",
    traits: ["Điềm tĩnh", "Thanh thản", "Vị tha", "Sâu sắc"],
  },
  DIOR: {
    code: "DIOR",
    name: "Dior-s — Quý Tộc Sang Chảnh",
    tagline: "Thà nhịn ăn tối chứ quyết không thể sống thiếu cái đẹp!",
    bio: "Bạn là tín đồ cuồng nhiệt của thẩm mỹ và cái đẹp nghệ thuật. Bạn không chấp nhận sự xuề xòa, nhạt nhẽo hay thiếu chỉn chu. Từ gu ăn mặc, giao diện điện thoại cho tới góc học tập của bạn đều phải xịn xò và chuẩn 'aesthetic'.",
    superpower: "Gu nghệ thuật tinh tế vượt trội, khả năng tận hưởng cuộc sống phong phú và khí chất sang sang.",
    kryptonite: "Ví tiền thường xuyên rơi vào trạng thái 'báo động đỏ' do ngẫu hứng chốt đơn hàng hiệu hoặc đồ đẹp.",
    quote: "“Cuộc đời ngắn lắm, tại sao phải chọn thứ nhạt nhẽo khi mình có thể chọn thứ sang xịn mịn?”",
    advice: "Hãy nhớ trích lập quỹ tiết kiệm trước khi chốt đơn món đồ xa xỉ tiếp theo nhé Quý Tộc ơi!",
    exampleScenario: "Dù chỉ đi ra tạp hóa đầu ngõ mua gói mì tôm, bạn vẫn phối đồ nguyên set chỉn chu, xịt nước hoa thơm phức và đeo kính mát cực ngầu!",
    traits: ["Sang chảnh", "Gu cao", "Tế nhị", "Hoàn hảo"],
  },
  JOKER: {
    code: "JOKER",
    name: "JOKE-R — Hề Sĩ Vui Vẻ",
    tagline: "Chiến thần pha trò, nơi đâu có bạn ở đó có tiếng cười rộn rã!",
    bio: "Bạn là chiếc máy phát năng lượng hài hước của mọi cuộc họp mặt. Nơi nào có bạn xuất hiện, không khí ở đó lập tức rộn rã tiếng cười và meme sống động. Bạn có tài năng thiên bẩm biến mọi nỗi u ủ u ám thành câu chuyện cười té ghế.",
    superpower: "Năng lượng tích cực dồi dào, khả năng giải tỏa căng thẳng siêu đẳng cho tập thể.",
    kryptonite: "Thường giấu nỗi buồn cá nhân đằng sau nụ cười, khó mở lòng khi chính mình bị tổn thương.",
    quote: "“Cuộc đời là một vở hài kịch, tại sao chúng ta không vừa nhai bắp rang vừa cười chứ?”",
    advice: "Bạn không cần phải lúc nào cũng gánh vai 'hề sĩ'. Bạn có quyền buồn, có quyền khóc và cần được ôm vỗ về!",
    exampleScenario: "Thấy không khí buổi họp nhóm đang căng thẳng vì bài làm dở tệ, bạn lập tức làm biểu cảm mặt hề và bắt chước giọng nói của nhân vật hoạt hình làm cả nhóm cười sặc sụa.",
    traits: ["Hài hước", "Năng lượng", "Vui vẻ", "Hòa đồng"],
  },
  DEAD: {
    code: "DEAD",
    name: "DEAD — Chiến Binh Bất Tử",
    tagline: "Tái sinh từ nghịch cảnh, càng vùi dập càng lì lợm bước tiếp!",
    bio: "Bạn tưởng chừng như đã trải qua 81 kiếp nạn của cuộc đời nhưng vẫn lầm lì đứng dậy bước tiếp. Càng bị số phận vùi dập hay thất bại, bạn lại càng tái sinh mạnh mẽ hơn. Trái tim bạn sắt đá và lý trí đến mức khiến người khác phải nể sợ.",
    superpower: "Sức chịu đựng vô hạn, ý chí kiên cường không gì quật ngã được, khả năng phục hồi siêu tốc.",
    kryptonite: "Dễ nhìn cuộc đời qua lăng kính nghi ngờ u uất, khó mở lòng tin tưởng ai hoàn toàn.",
    quote: "“Những gì không tiêu diệt được tôi sẽ chỉ làm cho tôi thêm lì lợm và đáng sợ hơn!”",
    advice: "Thế giới này vẫn còn nhiều điều vô cùng ấm áp, hãy mở cửa trái tim đón nhận chút ánh nắng nhé!",
    exampleScenario: "Bị điểm kém bài thi quan trọng, bị gạch tên khỏi dự án và mới chia tay người yêu trong cùng 1 tuần, bạn vẫn lẳng lặng đi tập gym, ăn bữa tối đầy đủ chất và lên kế hoạch phục thù vào sáng hôm sau!",
    traits: ["Kiên cường", "Lì lợm", "Tái sinh", "Bất tử"],
  },
  ZZZZ: {
    code: "ZZZZ",
    name: "ZZZZ — Ẩn Sĩ Mộng Mơ",
    tagline: "Thánh ngủ vũ trụ, vương quốc thực sự nằm trong giấc mơ!",
    bio: "Bạn có thể ngủ ở mọi tư thế, mọi thời điểm và mọi không gian. Với bạn, giấc ngủ không chỉ là nghỉ ngơi mà là chiếc cổng dẫn vào vương quốc mộng mơ giàu sang sáng tạo nhất. Bạn cực kỳ ghét những chuyện ganh đua bon chen mệt mỏi.",
    superpower: "Trí tưởng tượng bay bổng vô tận, tâm hồn bình yên, khả năng tái tạo năng lượng thần tốc.",
    kryptonite: "Dễ bỏ lỡ những cơ hội tuyệt vời đời thực chỉ vì... bận ngủ nướng thêm 15 phút.",
    quote: "“Nói ít thôi, tắt đèn giùm để tôi ngủ thêm 5 phút nữa...”",
    advice: "Đặt chiếc báo thức ra xa giường và bắt tay vào biến những giấc mơ tuyệt đẹp thành hiện thực đi nào!",
    exampleScenario: "Cuối tuần bạn có thể ngủ liền một mạch từ 11h đêm hôm trước tới 2h chiều hôm sau, dậy ăn một bát mì rồi lại trùm chăn ngủ tiếp chuyến 'overnight' thứ hai!",
    traits: ["Mộng mơ", "Bình yên", "Tự do", "Thư thái"],
  },
  ATMR: {
    code: "ATMR",
    name: "ATM-er — Cây ATM Biết Đi",
    tagline: "Hào sảng vô bờ, bảo bối tài chính của lũ bạn thân!",
    bio: "Bạn là kiểu người hào sảng, phóng khoáng và luôn là người nhảy vào giành thanh toán chầu ăn uống đầu tiên. Thấy bạn bè hay người xung quanh gặp khó khăn là tay bạn tự động rút ví ra hỗ trợ không cần suy tính.",
    superpower: "Tốt bụng tuyệt đối, hào sảng rộng lượng, được mọi người quý mến và tin tưởng tuyệt đối.",
    kryptonite: "Dễ bị kẻ xấu lợi dụng lòng tốt và ví tiền luôn trong tình trạng 'vơi nhanh hơn nước chảy'.",
    quote: "“Thôi để đó tôi lo! Có nhiêu đâu mà phải lăn tăn!”",
    advice: "Hãy học cách nói 'KHÔNG' khi cần thiết và biết tự chăm sóc quỹ tài chính của mình trước nhé!",
    exampleScenario: "Đi ăn chè với đám bạn, khi cả hội đang loay hoay quét mã QR chia tiền lẻ tới từng nghìn, bạn nhẹ nhàng phẩy tay: 'Thôi tao mời hết, mai mốt mời lại trà sữa là được!'",
    traits: ["Hào sảng", "Tốt bụng", "Rộng lượng", "Uy tín"],
  },
  THANK: {
    code: "THANK",
    name: "THAN-K — Người Biết Ơn",
    tagline: "Trái tim biết ơn, trân trọng từng điều nhỏ bé ấm áp!",
    bio: "Tâm hồn bạn tràn ngập tình yêu thương và sự biết ơn cuộc đời. Thấy chú mèo hoang đi qua bạn mỉm cười, thấy hạt mưa rơi bạn cảm ơn vì thiên nhiên được tưới mát. Bạn luôn tìm thấy mặt tích cực và sự ấm áp trong mọi hoàn cảnh.",
    superpower: "Lan tỏa năng lượng chữa lành ấm áp, biết trân trọng từng khoảnh khắc nhỏ bé diệu kỳ.",
    kryptonite: "Dễ xúc động, nhạy cảm quá mức với thái độ hay lời nói vô tình của người khác.",
    quote: "“Cảm ơn vì chúng ta vẫn còn khỏe mạnh và được gặp nhau ngày hôm nay!”",
    advice: "Sự biết ơn của bạn là một món quà vô giá, hãy giữ vững trái tim ấm áp này trước sóng gió nhé!",
    exampleScenario: "Được bạn mua giùm một ly trà sữa 50% đường, bạn không chỉ cảm ơn rối rít mà còn viết một dòng tin nhắn dài 5 dòng khen ly trà sữa ngon nhất trần đời!",
    traits: ["Biết ơn", "Ấm áp", "Nhạy cảm", "Chân thành"],
  },
  OHNO: {
    code: "OHNO",
    name: "OH-NO — Thánh Hoảng Hốt",
    tagline: "Chuyên gia lo xa của vũ trụ, luôn chuẩn bị cho kịch bản tồi tệ nhất!",
    bio: "Bạn là chiếc 'rada rủi ro' biết đi. Đi du lịch 2 ngày nhưng bạn mang theo cả một tiệm thuốc thu nhỏ, 3 cái sạc dự phòng và 5 bộ kịch bản phòng tai nạn. Bạn luôn chuẩn bị sẵn sàng cho tình huống tồi tệ nhất có thể xảy ra.",
    superpower: "Khả năng dự phòng rủi ro và cẩn trọng tuyệt đối, không bao giờ bị bị động.",
    kryptonite: "Tự làm bản thân kiệt sức và căng thẳng bởi 1001 kịch bản lo xa chưa bao giờ xảy ra trong thực tế.",
    quote: "“OH NO! Nhỡ đâu tí nữa trời mưa to rồi sập điện rồi mất luôn file bài tập thì sao?!”",
    advice: "Hít thở sâu một hơi nào! 99% những điều tồi tệ bạn lo lắng trong đầu sẽ không xảy ra đâu!",
    exampleScenario: "Trước buổi đi picnic 1 ngày, bạn kiểm tra dự báo thời tiết ở 3 ứng dụng khác nhau, mua sẵn 5 chiếc áo mưa bộ, 2 ô gấp gọn và bao bọc ni-lông cẩn thận cho từng chiếc điện thoại!",
    traits: ["Cẩn trọng", "Lo xa", "Chu đáo", "Dự phòng"],
  },
  GOGO: {
    code: "GOGO",
    name: "GOGO — Chiến Thần Năng Lượng",
    tagline: "Không bao giờ ngồi yên, cháy hết mình với đam mê rực rỡ!",
    bio: "Bạn là ngọn lửa năng lượng không bao giờ tắt. Vừa xong việc này là bạn nháo nhào nhảy sang việc khác, lúc nào cũng trong trạng thái hừng hực khí thế rực rỡ. Bạn truyền cảm hứng mạnh mẽ cho bất kỳ ai ở gần.",
    superpower: "Tốc độ hành động cực nhanh, tinh thần xông xáo bùng nổ, truyền lửa tuyệt vời.",
    kryptonite: "Dễ rơi vào trạng thái kiệt sức (burnout) tháo gỡ không kịp do không biết dừng lại nghỉ ngơi.",
    quote: "“GOGO! Chiến ngay thôi chờ gì nữa anh em ơi! Làm liền cho nóng!”",
    advice: "Hãy dành thời gian nạp lại pin nhé chiến thần, chạy nhanh quá dễ đứt xích lắm đó!",
    exampleScenario: "Vừa có ý tưởng làm một kênh TikTok du lịch, ngay đêm đó bạn đã quay xong 3 video, dựng xong clip và viết caption sẵn sàng đăng bài lúc 7h sáng!",
    traits: ["Năng nổ", "Tốc độ", "Nhiệt huyết", "Truyền cảm hứng"],
  },
  LOVR: {
    code: "LOVR",
    name: "LOVE-R — Kẻ Lãng Mạn Mộng Mơ",
    tagline: "Thở bằng tình yêu, sống bằng sự ngọt ngào lãng mạn!",
    bio: "Bạn sống vì tình yêu và thở bằng sự ngọt ngào. Xem một bộ phim tình cảm Hàn Quốc là bạn khóc trôi nhà. Bạn luôn tin vào những câu chuyện cổ tích, tình yêu sét đánh và những lời hứa hẹn vĩnh cửu.",
    superpower: "Giàu cảm xúc sâu sắc, biết cách tạo ra bất ngờ và sự ngọt ngào làm đối phương lụi tim.",
    kryptonite: "Dễ bị tổn thương sâu sắc khi thực tế tình yêu không hồng như trong phim.",
    quote: "“Tình yêu chính là sức mạnh duy nhất có thể cứu rỗi thế giới u ám này!”",
    advice: "Yêu thương người khác là tuyệt vời, nhưng hãy nhớ dành trọn tình yêu cho chính bản thân mình trước tiên nhé!",
    exampleScenario: "Kỷ niệm 1 tháng quen nhau, bạn tự tay chuẩn bị một hộp quà handmade chứa 30 lá thư tay nhỏ nhắn dặn dò đối phương đọc mỗi ngày!",
    traits: ["Lãng mạn", "Ngọt ngào", "Giàu cảm xúc", "Chân thành"],
  },
  MUMM: {
    code: "MUMM",
    name: "MUM — Người Mẹ Quốc Dân",
    tagline: "Chu đáo tới từng chân răng, bảo bọc chăm sóc mọi người!",
    bio: "Bạn chu đáo tới mức làm người khác xúc động. Đi chơi nhóm bạn luôn mang theo khăn giấy khô, khăn giấy ướt, nước rửa tay, kẹo ngậm ho, sạc dự phòng và cả đồ ăn nhẹ cho cả hội.",
    superpower: "Khả năng chăm sóc bảo bọc tuyệt vời, tạo ra cảm giác an toàn và ấm áp vô bờ.",
    kryptonite: "Hay ôm đồm lo lắng thái quá cho chuyện của người khác mà quên mất bản thân mình cũng cần chăm sóc.",
    quote: "“Con ăn cơm chưa? Nhớ uống nhiều nước vào đấy nhé, thức khuya xấu da lắm!”",
    advice: "Hãy thả lỏng để mọi người tự trưởng thành chút đi nào, bạn cũng cần được người khác chăm sóc mà!",
    exampleScenario: "Đi leo núi cùng hội bạn, khi ai đó bị trầy xước nhẹ ở tay, bạn lập tức rút từ balo ra bông băng, thuốc đỏ, băng cá nhân hoạt hình và chai xịt tiệt trùng!",
    traits: ["Chu đáo", "Bảo bọc", "Ấm áp", "Tận tụy"],
  },
  FAKE: {
    code: "FAKE",
    name: "FAKE — Bậc Thầy Núp Bóng",
    tagline: "Tắc kè hoa xã hội, sở hữu 100 chiếc mặt nạ ứng biến!",
    bio: "Bạn là tắc kè hoa thực sự của thế giới tính cách. Gặp người nghiêm túc bạn biến thành doanh nhân tri thức, gặp người quậy phá bạn biến thành dân chơi cháy phố. Bạn nhập vai mượt mà trong mọi hoàn cảnh xã hội.",
    superpower: "Khả năng thích nghi đỉnh cao, giao thiệp rộng rãi không có bất kỳ rào cản nào.",
    kryptonite: "Thỉnh thoảng cảm thấy hoang mang vì quên mất con người thật của mình thực sự muốn gì.",
    quote: "“Tùy đối tượng thôi bạn ơi, tôi có cả một bộ sưu tập 100 chiếc mặt nạ ứng biến mà!”",
    advice: "Hãy dành một không gian riêng tư để thả lỏng hoàn toàn và sống thật với chính mình nhé!",
    exampleScenario: "Vừa mới ngồi trò chuyện cực kỳ trang trọng với thầy cô giáo trưởng khoa, 5 phút sau bước ra ngoài cổng trường bạn đã có thể bắn slang chất lừ với nhóm bạn thân!",
    traits: ["Linh hoạt", "Thích nghi", "Khéo léo", "Nhanh trí"],
  },
  OJBK: {
    code: "OJBK",
    name: "OJBK — Thánh Sao Cũng Được",
    tagline: "Dễ tính nhất hành tinh, lành tính vô bờ bến!",
    bio: "Bạn là người dễ tính nhất trên đời. Hỏi ăn gì cũng 'gì cũng được', hỏi đi đâu cũng 'sao cũng hợp lý'. Bạn cực kỳ lành tính, không thích va chạm hay tranh chấp đúng sai với ai.",
    superpower: "Dễ sống, hòa đồng, mang lại cảm giác cực kỳ dễ chịu và thoải mái cho người xung quanh.",
    kryptonite: "Thiếu chính kiến riêng, dễ bị cuốn theo quyết định của người khác mà chịu thiệt thòi.",
    quote: "“OK dĩ nhiên rồi (OJBK)! Sao cũng được hết đó, mọi người chốt đi!”",
    advice: "Thỉnh thoảng hãy dũng cảm nói ra ý kiến và mong muốn thực sự của bản thân nhé!",
    exampleScenario: "Nhóm bạn cãi nhau 30 phút vì chọn giữa trà sữa và cà phê, bạn ngồi húp ngụm nước lọc mỉm cười: 'Uống cái nào tao cũng uống được hết á, chọn đại đi!'",
    traits: ["Dễ tính", "Lành tính", "Hòa nhã", "Thoải mái"],
  },
  MALO: {
    code: "MALO",
    name: "MALO — Khỉ Nho Hóm Hỉnh",
    tagline: "Lém lỉnh nhanh trí, ngôi sao của những trò đùa bất ngờ!",
    bio: "Bạn lém lỉnh, nhanh trí và luôn sở hữu những trò đùa bất ngờ làm người khác 'ngơ ngác bật ngửa'. Bạn có đầu óc nảy số liên tục và không bao giờ chịu thua trong các cuộc khẩu chiến vui vẻ.",
    superpower: "Linh hoạt, phản ứng ứng biến cực nhanh, đầu óc nảy số ý tưởng độc lạ.",
    kryptonite: "Đôi khi đùa quá đà hoặc cà khịa không đúng lúc khiến người khác chạnh lòng.",
    quote: "“Chuyện nhỏ như con thỏ! Trò này để tôi ra tay chỉ cho mà xem!”",
    advice: "Hài hước đúng lúc đúng chỗ sẽ giúp bạn trở thành ngôi sao sáng nhất trong mắt mọi người!",
    exampleScenario: "Trong một trò chơi nối chữ hoặc đố mẹo, bạn đưa ra những câu trả lời vừa vô lý vừa thuyết phục làm cả phòng phải vỗ tay thán phục!",
    traits: ["Lém lỉnh", "Nhanh trí", "Hóm hỉnh", "Ứng biến"],
  },
  WOCI: {
    code: "WOCI",
    name: "WOC! — Thánh Ôi Chao",
    tagline: "Biểu cảm sống động như GIF, khán giả nhiệt thành nhất vũ trụ!",
    bio: "Biểu cảm trên khuôn mặt bạn sống động không khác gì những tấm ảnh GIF hài hước. Bất kỳ sự việc nhỏ nào cũng có thể làm bạn trầm ồ thán phục, mắt mắt miệng há hộc và tạo năng lượng bùng nổ cho câu chuyện.",
    superpower: "Chân thật, giàu cảm xúc rực rỡ, làm khán giả tuyệt vời nhất nâng tầm câu chuyện của người khác.",
    kryptonite: "Dễ bị cuốn theo cảm xúc bộc phát tức thời mà thiếu sự trầm tĩnh suy xét.",
    quote: "“WOC! Thật luôn?! Trời ơi không thể tin nổi luôn đó má ơi!”",
    advice: "Giữ chút bình tĩnh để quan sát toàn cảnh trước khi đưa ra phản ứng bùng nổ nhé!",
    exampleScenario: "Bạn bè vừa nghe một tin đồn nho nhỏ trên mạng, bạn đã thốt lên 'WOC!' với ánh mắt mở to kinh ngạc như thể vừa chứng kiến đĩa bay người ngoài hành tinh đáp xuống!",
    traits: ["Sống động", "Chân thật", "Nhiệt thành", "Cảm xúc"],
  },
  THINK: {
    code: "THINK",
    name: "THIN-K — Nhà Triết Học Đêm Muộn",
    tagline: "Trăn trở nhân sinh, phân tích bản chất quy luật vũ trụ!",
    bio: "Mỗi khi đêm về là lúc đầu óc bạn tự động bật chế độ 'phân tích vũ trụ'. Bạn luôn trăn trở về ý nghĩa cuộc sống, bản chất con người, nguồn gốc của cảm xúc và những quy luật ẩn sau vạn vật.",
    superpower: "Tư duy sâu sắc thấu đáo, logic mạch lạc, nhìn xuyên qua vẻ bề ngoài để thấy bản chất.",
    kryptonite: "Hay bị mất ngủ vì suy nghĩ quá nhiều chuyện trên trời dưới đất hoặc rơi vào 'overthinking'.",
    quote: "“Tại sao chúng ta lại tồn tại? Mục đích thực sự của vũ trụ này là gì nhỉ?”",
    advice: "Đôi khi cuộc sống chỉ đơn giản là ăn một bữa thật ngon và ngủ một giấc thật sâu thôi bạn ơi!",
    exampleScenario: "2h sáng, thay vì ngủ, bạn ngồi nhìn trần nhà và suy ngẫm xem liệu thời gian có thực sự tồn tại hay chỉ là sản phẩm do trí não con người tự tưởng tượng ra!",
    traits: ["Sâu sắc", "Triết học", "Tư duy", "Logic"],
  },
  SHIT: {
    code: "SHIT",
    name: "SHIT — Chiến Thần Thẳng Thắn",
    tagline: "Khẩu xà tâm phật, miệng gắt gỏng nhưng lòng ấm áp như nắng hè!",
    bio: "Bạn thuộc tuýp 'khẩu xà tâm phật' điển hình. Miệng hay cào phím gắt gỏng, nói lời thẳng thắn không kiêng nể, nhưng hễ thấy bạn bè gặp chuyện bất bình là bạn lập tức nhảy vào xả thân bảo vệ không tính toán.",
    superpower: "Thẳng thắn tuyệt đối, không giả tạo hai mặt, cực kỳ trung thành và nghĩa khí với bạn bè.",
    kryptonite: "Lời nói thẳng như ruột ngựa dễ làm tổn thương những tâm hồn mỏng mảnh yếu đuối.",
    quote: "“Nói thẳng ra là dở tệ! Nhưng thôi đưa đây tao chỉ cho làm, nhìn ngứa mắt quá!”",
    advice: "Tiết chế lại sự gắt gao xíu nhé, một món ăn ngon luôn cần chút gia vị ngọt ngào mà!",
    exampleScenario: "Bạn thân làm bài slide thuyết trình quá xấu, bạn chê ngay 'Xấu như ma cấu!', rồi thức nguyên đêm làm lại cho nó một bản slide đẹp lung linh!",
    traits: ["Thẳng thắn", "Chân thật", "Trung thành", "Bản lĩnh"],
  },
  POOR: {
    code: "POOR",
    name: "POOR — Thánh Than Nghèo",
    tagline: "Mở miệng là than nghèo, nhưng sổ tiết kiệm luôn có quỹ xịn!",
    bio: "Hễ mở miệng ra là bạn than 'Tôi nghèo lắm, không có tiền đâu', nhưng trong tài khoản tiết kiệm của bạn luôn có quỹ dự phòng xịn xò. Bạn thích sống thực tế, tiết kiệm và quản lý tài chính cực kỳ chặt chẽ.",
    superpower: "Quản lý tài chính cá nhân đỉnh cao, thực tế, không bao giờ lãng phí tiền bạc vào thứ vô bổ.",
    kryptonite: "Đôi khi quá keo kiệt và khắt khe với chính những nhu cầu hưởng thụ của bản thân.",
    quote: "“Thôi đắt lắm, món này tới 50k lận, tôi không có tiền đâu...”",
    advice: "Hãy thưởng cho bản thân những niềm vui xứng đáng sau những nỗ lực làm việc vất vả nhé!",
    exampleScenario: "Than hết tiền cả tháng, nhưng khi bạn bè cần vay gấp một khoản tiền để đóng học phí, bạn chuyển khoản ngay lập tức trong 30 giây!",
    traits: ["Thực tế", "Tiết kiệm", "Quản lý tốt", "Cẩn thận"],
  },
  IMSB: {
    code: "IMSB",
    name: "IMSB — Thánh Ngu Ngơ Trẻ Thơ",
    tagline: "Tâm hồn trong sáng như tờ giấy trắng, nhìn đời qua màu hồng!",
    bio: "Tâm hồn bạn trong sáng ngây thơ như một đứa trẻ. Ai nói gì bạn cũng tin ngay, ngây thơ vô số tội và luôn nhìn thế giới qua lăng kính màu hồng ngập tràn niềm tin và sự hy vọng ngộ nghĩnh.",
    superpower: "Đáng yêu bẩm sinh, chân thành thuần khiết, mang lại sự nhẹ nhõm vô tư cho người bên cạnh.",
    kryptonite: "Dễ bị kẻ xấu lừa gạt hoặc lợi dụng bởi những lời đường mật ngọt ngào.",
    quote: "“Ủa vậy hả?! Sao tôi không biết gì hết vậy ta? Thật luôn hả?”",
    advice: "Giữ vững sự ngây thơ đáng yêu, nhưng nhớ trang bị thêm chút cảnh giác trước thế giới nhé!",
    exampleScenario: "Bạn bè troll bảo 'Uống nước dừa buổi tối sẽ biến thành tiên cá', bạn cũng mắt tròn mắt dẹt lắng nghe rồi suy nghĩ có nên thử hay không!",
    traits: ["Trong sáng", "Trẻ thơ", "Ngây thơ", "Đáng yêu"],
  },
  FUCK: {
    code: "FUCK",
    name: "FUCK — Kẻ Hoang Dã Phá Cách",
    tagline: "Ghét mọi quy tắc gò bó, tự do tuyệt đối là lẽ sống!",
    bio: "Bạn sinh ra là để phá vỡ các giới hạn. Bạn cực kỳ ghét sự gò bó, luật lệ cứng nhắc hay những khuôn mẫu nhàm chán. Bạn sống tự do, phóng khoáng và luôn đưa ra những ý tưởng dị biệt làm ai cũng kinh ngạc.",
    superpower: "Sáng tạo bùng nổ, dũng cảm phá vỡ giới hạn, cá tính mạnh mẽ không đụng hàng.",
    kryptonite: "Dễ nổi loạn, khó làm việc trong môi trường mang tính kỷ luật và quy tắc cứng nhắc.",
    quote: "“Quy tắc sinh ra là để phá vỡ mà! Sao phải sống theo cách người khác vẽ sẵn?”",
    advice: "Tự do là tuyệt vời, nhưng giữ một chút kỷ luật nền tảng sẽ giúp bạn tiến xa hơn nữa!",
    exampleScenario: "Bài tập yêu cầu làm báo cáo Word 5 trang, bạn quyết định quay một đoạn phim ngắn 3 phút với hiệu ứng visual ảo diệu làm thầy cô phải cho điểm tối đa vì quá sáng tạo!",
    traits: ["Hoang dã", "Phá cách", "Tự do", "Sáng tạo"],
  },
  IMFW: {
    code: "IMFW",
    name: "IMFW — Thánh Vô Dụng Yêu Đời",
    tagline: "Triết lý nằm yên mặc kệ đời, an nhiên tận hưởng từng phút giây!",
    bio: "Triết lý sống đỉnh cao của bạn là: 'Nằm yên mặc kệ sóng gió cuộc đời'. Bạn không ganh đua thắng thua với ai, thong thả tận hưởng những niềm vui nhỏ bé như ăn một cái bánh ngon, nghe một bài nhạc hay.",
    superpower: "Thoải mái, không áp lực, tâm lý vô vi tự tại, không bao giờ lo âu trầm cảm.",
    kryptonite: "Thiếu chí tiến thủ, dễ hài lòng với hiện tại và lười bứt phá khỏi vùng an toàn.",
    quote: "“Gió tầng nào gặp mây tầng đó, thôi tôi nằm tầng 1 cho nó lành và mát!”",
    advice: "Thỉnh thoảng hãy thử đặt một mục tiêu nhỏ để thử thách sức bứt phá của bản thân xem sao!",
    exampleScenario: "Cả lớp rủ nhau đăng ký thi học sinh giỏi, bạn nhẹ nhàng từ chối rồi ở nhà nằm võng đung đưa ăn dưa hấu xem phim hoạt hình!",
    traits: ["An nhiên", "Thư thái", "Thoải mái", "Không gánh nặng"],
  },
  HHHH: {
    code: "HHHH",
    name: "HHHH — Bậc Thầy Giả Chết",
    tagline: "Khi có biến lập tức tàng hình, ẩn thân chờ sóng êm biển lặng!",
    bio: "Bạn là bậc thầy giấu mình đỉnh cao của hành tinh. Khi có drama, xung đột hay biến cố xảy ra, bạn lập tức bật chế độ 'giả chết tàng hình', chờ sóng êm biển lặng rồi mới thong thả bước ra như chưa có gì xảy ra.",
    superpower: "Khả năng sinh tồn tuyệt đối, né tránh rắc rối và giữ an toàn bản thân thượng thừa.",
    kryptonite: "Hay né tránh xung đột ngay cả khi cần dũng cảm đứng ra lên tiếng giải quyết.",
    quote: "“Tôi không có ở đây nha, tôi chỉ là hạt bụi vô hình thôi, mọi người cứ tự nhiên...”",
    advice: "Dũng cảm lên bạn ơi! Đôi khi bước ra ánh sáng đối mặt sẽ giúp bạn khám phá ra sức mạnh phi thường của mình!",
    exampleScenario: "Thấy hai nhóm bạn sắp sửa cãi nhau to trong quán ăn, bạn lẳng lặng đeo khẩu trang, cầm ly nước đi từ từ ra cửa như một vị khách xa lạ!",
    traits: ["Ẩn thân", "Tránh rắc rối", "Sinh tồn", "Khéo léo"],
  },
};

export function getWittyProfile(code: string): WittyPersonalityProfile {
  if (!code) return WITTY_PERSONALITY_PROFILES.BOSS;
  const upper = code.trim().toUpperCase();

  // Code normalization mapping
  const normalizedKey = 
    upper === "ATM" ? "ATMR" :
    upper === "DIOR" ? "DIOR" :
    upper === "JOKER" || upper === "JOKE-R" || upper === "JOKE" ? "JOKER" :
    upper === "LOVR" || upper === "LOVE-R" || upper === "LOVE" ? "LOVR" :
    upper === "MUM" ? "MUMM" :
    upper === "OHNO" || upper === "OH-NO" ? "OHNO" :
    upper === "THANK" || upper === "THAN-K" ? "THANK" :
    upper === "THINK" || upper === "THIN-K" ? "THINK" :
    upper === "WOC" || upper === "WOCI" ? "WOCI" :
    upper;

  return WITTY_PERSONALITY_PROFILES[normalizedKey] || WITTY_PERSONALITY_PROFILES[code] || {
    code,
    name: `${code} — Linh Thú Độc Bản`,
    tagline: "Một linh thú mang trường năng lượng đặc biệt!",
    bio: "Linh thú độc đáo mang đến góc nhìn mới mẻ và thú vị về tính cách của bạn trong thế giới TESTDII.",
    superpower: "Độc bản, khác biệt, khó nắm bắt.",
    kryptonite: "Đôi khi làm người khác bối rối vì sự độc đáo.",
    quote: "“Tôi là chính tôi, không đụng hàng!”",
    advice: "Hãy tiếp tục giữ vững bản sắc riêng của bạn!",
    exampleScenario: "Luôn xuất hiện với phong cách riêng biệt và làm mọi người bất ngờ bởi những suy nghĩ độc lạ!",
    traits: ["Độc bản", "Bí ẩn", "Cá tính"],
  };
}
